language: python
python:
    - "3.6"
before_install:
    - pip install -U pip
    - pip install -U pytest pytest-cov
    - pip install codecov
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - pytest --cov funkyAD
after_success:
    - codecov
